version: 0.2
env:
  variables:
    SRC_DIR: /go/src/handler
    ENV_NAME: pj

phases:
  install:
    commands:
      # Debugging
      - env | sort
      # Work inside GOPATH
      - ln -s ${CODEBUILD_SRC_DIR} ${SRC_DIR}
      - cd ${SRC_DIR}
      # Debugging
      - pwd
      - find .
      # Install CI dependencies
      - go get -t ./...
      - go get -u golang.org/x/lint/golint

  pre_build:
    commands:
      # Runs megacheck
      - golint -set_exit_status
      # Run all tests included with the application
      - go test ./...

  build:
    commands:
      # Build the go application
      - go build -o main main.go

artifacts:
  files:
    - main
  name: $ENV_NAME-lambda-$(date +%Y-%m-%d).zip 